module.exports = [
    {
        "city": "Karachi",
        "state": "Sindh",
        "country": "Pakistan",
        "population_proper": "11624219",
        "iso2": "PK",
        "capital": "state",
        "latitude": "24.9056",
        "longitude": "67.0822",
        "population": "12130000"
    },
    {
        "city": "Lahore",
        "state": "Punjab",
        "country": "Pakistan",
        "population_proper": "6310888",
        "iso2": "PK",
        "capital": "state",
        "latitude": "31.549722",
        "longitude": "74.343611",
        "population": "6577000"
    },
    {
        "city": "Faisalabad",
        "state": "Punjab",
        "country": "Pakistan",
        "population_proper": "2506595",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "31.416667",
        "longitude": "73.083333",
        "population": "2617000"
    },
    {
        "city": "Serai",
        "state": "Khyber Pakhtunkhwa",
        "country": "Pakistan",
        "population_proper": "1860310",
        "iso2": "PK",
        "capital": "",
        "latitude": "34.73933",
        "longitude": "72.335655",
        "population": "1860310"
    },
    {
        "city": "Rawalpindi",
        "state": "Punjab",
        "country": "Pakistan",
        "population_proper": "1743101",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "33.597331",
        "longitude": "73.047904",
        "population": "1858000"
    },
    {
        "city": "Multan",
        "state": "Punjab",
        "country": "Pakistan",
        "population_proper": "1437230",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "30.196789",
        "longitude": "71.478241",
        "population": "1522000"
    },
    {
        "city": "Gujranwala",
        "state": "Punjab",
        "country": "Pakistan",
        "population_proper": "1384471",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "32.155667",
        "longitude": "74.187052",
        "population": "1513000"
    },
    {
        "city": "Hyderabad City",
        "state": "Sindh",
        "country": "Pakistan",
        "population_proper": "1386330",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "25.396891",
        "longitude": "68.377183",
        "population": "1459000"
    },
    {
        "city": "Peshawar",
        "state": "Khyber Pakhtunkhwa",
        "country": "Pakistan",
        "population_proper": "1218773",
        "iso2": "PK",
        "capital": "state",
        "latitude": "34.008",
        "longitude": "71.578488",
        "population": "1303000"
    },
    {
        "city": "Abbottabad",
        "state": "Khyber Pakhtunkhwa",
        "country": "Pakistan",
        "population_proper": "881000",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "34.1463",
        "longitude": "73.211684",
        "population": "1183647"
    },
    {
        "city": "Islamabad",
        "state": "Islamabad",
        "country": "Pakistan",
        "population_proper": "601600",
        "iso2": "PK",
        "capital": "primary",
        "latitude": "33.69",
        "longitude": "73.0551",
        "population": "780000"
    },
    {
        "city": "Quetta",
        "state": "Balochistan",
        "country": "Pakistan",
        "population_proper": "733675",
        "iso2": "PK",
        "capital": "state",
        "latitude": "30.184138",
        "longitude": "67.00141",
        "population": "768000"
    },
    {
        "city": "Bannu",
        "state": "Khyber Pakhtunkhwa",
        "country": "Pakistan",
        "population_proper": "550000",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "32.985414",
        "longitude": "70.602701",
        "population": "622419"
    },
    {
        "city": "Bahawalpur",
        "state": "Punjab",
        "country": "Pakistan",
        "population_proper": "552607",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "29.4",
        "longitude": "71.683333",
        "population": "552607"
    },
    {
        "city": "Sargodha",
        "state": "Punjab",
        "country": "Pakistan",
        "population_proper": "542603",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "32.083611",
        "longitude": "72.671111",
        "population": "542603"
    },
    {
        "city": "Sialkot City",
        "state": "Punjab",
        "country": "Pakistan",
        "population_proper": "477396",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "32.499101",
        "longitude": "74.52502",
        "population": "477396"
    },
    {
        "city": "Sukkur",
        "state": "Sindh",
        "country": "Pakistan",
        "population_proper": "417767",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "27.705164",
        "longitude": "68.857383",
        "population": "417767"
    },
    {
        "city": "Larkana",
        "state": "Sindh",
        "country": "Pakistan",
        "population_proper": "364033",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "27.558985",
        "longitude": "68.212035",
        "population": "364033"
    },
    {
        "city": "Sheikhupura",
        "state": "Punjab",
        "country": "Pakistan",
        "population_proper": "361303",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "31.713056",
        "longitude": "73.978333",
        "population": "361303"
    },
    {
        "city": "Mibrpur Khas",
        "state": "Sindh",
        "country": "Pakistan",
        "population_proper": "215657",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "25.5251",
        "longitude": "69.0159",
        "population": "356435"
    },
    {
        "city": "Rahibmyar Khan",
        "state": "Punjab",
        "country": "Pakistan",
        "population_proper": "353203",
        "iso2": "PK",
        "capital": "",
        "latitude": "28.419482",
        "longitude": "70.302386",
        "population": "353203"
    },
    {
        "city": "Kohat",
        "state": "Khyber Pakhtunkhwa",
        "country": "Pakistan",
        "population_proper": "151427",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "33.581958",
        "longitude": "71.449291",
        "population": "343027"
    },
    {
        "city": "Jhang Sadr",
        "state": "Punjab",
        "country": "Pakistan",
        "population_proper": "341210",
        "iso2": "PK",
        "capital": "",
        "latitude": "31.269811",
        "longitude": "72.316867",
        "population": "341210"
    },
    {
        "city": "Gujrat",
        "state": "Punjab",
        "country": "Pakistan",
        "population_proper": "301506",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "32.574204",
        "longitude": "74.075423",
        "population": "301506"
    },
    {
        "city": "Bardar",
        "state": "Khyber Pakhtunkhwa",
        "country": "Pakistan",
        "population_proper": "300424",
        "iso2": "PK",
        "capital": "",
        "latitude": "34.163737",
        "longitude": "72.011571",
        "population": "300424"
    },
    {
        "city": "Kasur",
        "state": "Punjab",
        "country": "Pakistan",
        "population_proper": "290643",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "31.115556",
        "longitude": "74.446667",
        "population": "290643"
    },
    {
        "city": "Dera Ghazi Khan",
        "state": "Punjab",
        "country": "Pakistan",
        "population_proper": "236093",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "30.056142",
        "longitude": "70.634766",
        "population": "236093"
    },
    {
        "city": "Masibwala",
        "state": "Punjab",
        "country": "Pakistan",
        "population_proper": "235695",
        "iso2": "PK",
        "capital": "",
        "latitude": "30.683333",
        "longitude": "73.066667",
        "population": "235695"
    },
    {
        "city": "Nawabshah",
        "state": "Sindh",
        "country": "Pakistan",
        "population_proper": "229504",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "26.248334",
        "longitude": "68.409554",
        "population": "229504"
    },
    {
        "city": "Okara",
        "state": "Punjab",
        "country": "Pakistan",
        "population_proper": "223648",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "30.808056",
        "longitude": "73.445833",
        "population": "223648"
    },
    {
        "city": "Gilgit",
        "state": "Gilgit-Baltistan",
        "country": "Pakistan",
        "population_proper": "31633",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "35.920007",
        "longitude": "74.313656",
        "population": "216760"
    },
    {
        "city": "Chiniot",
        "state": "Punjab",
        "country": "Pakistan",
        "population_proper": "201781",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "31.72",
        "longitude": "72.978889",
        "population": "201781"
    },
    {
        "city": "Sadiqabad",
        "state": "Punjab",
        "country": "Pakistan",
        "population_proper": "189876",
        "iso2": "PK",
        "capital": "",
        "latitude": "28.30623",
        "longitude": "70.130646",
        "population": "189876"
    },
    {
        "city": "Turbat",
        "state": "Balochistan",
        "country": "Pakistan",
        "population_proper": "75694",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "26.001224",
        "longitude": "63.048491",
        "population": "147791"
    },
    {
        "city": "Dera Ismail Khan",
        "state": "Khyber Pakhtunkhwa",
        "country": "Pakistan",
        "population_proper": "31737",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "31.832691",
        "longitude": "70.902398",
        "population": "101616"
    },
    {
        "city": "Chaman",
        "state": "Balochistan",
        "country": "Pakistan",
        "population_proper": "88568",
        "iso2": "PK",
        "capital": "",
        "latitude": "30.917689",
        "longitude": "66.45259",
        "population": "88568"
    },
    {
        "city": "Zhob",
        "state": "Balochistan",
        "country": "Pakistan",
        "population_proper": "50537",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "31.340817",
        "longitude": "69.449304",
        "population": "88356"
    },
    {
        "city": "Mehra",
        "state": "Khyber Pakhtunkhwa",
        "country": "Pakistan",
        "population_proper": "66486",
        "iso2": "PK",
        "capital": "",
        "latitude": "34.312817",
        "longitude": "73.220525",
        "population": "66486"
    },
    {
        "city": "Parachinar",
        "state": "Federally stateistered Tribal Areas",
        "country": "Pakistan",
        "population_proper": "55685",
        "iso2": "PK",
        "capital": "",
        "latitude": "33.895672",
        "longitude": "70.098875",
        "population": "55685"
    },
    {
        "city": "Gwadar",
        "state": "Balochistan",
        "country": "Pakistan",
        "population_proper": "23364",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "25.12163",
        "longitude": "62.325411",
        "population": "51901"
    },
    {
        "city": "Kundian",
        "state": "Punjab",
        "country": "Pakistan",
        "population_proper": "35406",
        "iso2": "PK",
        "capital": "",
        "latitude": "32.457747",
        "longitude": "71.478918",
        "population": "35406"
    },
    {
        "city": "Shahdad Kot",
        "state": "Sindh",
        "country": "Pakistan",
        "population_proper": "",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "27.847263",
        "longitude": "67.906789",
        "population": ""
    },
    {
        "city": "Haripur",
        "state": "Khyber Pakhtunkhwa",
        "country": "Pakistan",
        "population_proper": "",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "33.999967",
        "longitude": "72.934093",
        "population": ""
    },
    {
        "city": "Matiari",
        "state": "Sindh",
        "country": "Pakistan",
        "population_proper": "",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "25.59709",
        "longitude": "68.4467",
        "population": ""
    },
    {
        "city": "Dera Allahyar",
        "state": "Balochistan",
        "country": "Pakistan",
        "population_proper": "",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "28.373529",
        "longitude": "68.350778",
        "population": ""
    },
    {
        "city": "Lodhran",
        "state": "Punjab",
        "country": "Pakistan",
        "population_proper": "",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "29.540507",
        "longitude": "71.63357",
        "population": ""
    },
    {
        "city": "Batgram",
        "state": "Khyber Pakhtunkhwa",
        "country": "Pakistan",
        "population_proper": "",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "34.679637",
        "longitude": "73.026299",
        "population": ""
    },
    {
        "city": "Thatta",
        "state": "Sindh",
        "country": "Pakistan",
        "population_proper": "",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "24.747449",
        "longitude": "67.923528",
        "population": ""
    },
    {
        "city": "Bagh",
        "state": "Azad Kashmir",
        "country": "Pakistan",
        "population_proper": "",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "33.981106",
        "longitude": "73.776084",
        "population": ""
    },
    {
        "city": "Badibn",
        "state": "Sindh",
        "country": "Pakistan",
        "population_proper": "",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "24.655995",
        "longitude": "68.836997",
        "population": ""
    },
    {
        "city": "Mansehra",
        "state": "Khyber Pakhtunkhwa",
        "country": "Pakistan",
        "population_proper": "",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "34.330232",
        "longitude": "73.196788",
        "population": ""
    },
    {
        "city": "Ziarat",
        "state": "Balochistan",
        "country": "Pakistan",
        "population_proper": "",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "30.382444",
        "longitude": "67.725624",
        "population": ""
    },
    {
        "city": "Muzaffargarh",
        "state": "Punjab",
        "country": "Pakistan",
        "population_proper": "",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "30.072576",
        "longitude": "71.193788",
        "population": ""
    },
    {
        "city": "Tando Allahyar",
        "state": "Sindh",
        "country": "Pakistan",
        "population_proper": "",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "25.462626",
        "longitude": "68.719233",
        "population": ""
    },
    {
        "city": "Dera Murad Jamali",
        "state": "Balochistan",
        "country": "Pakistan",
        "population_proper": "",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "28.546568",
        "longitude": "68.223081",
        "population": ""
    },
    {
        "city": "Karak",
        "state": "Khyber Pakhtunkhwa",
        "country": "Pakistan",
        "population_proper": "",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "33.116334",
        "longitude": "71.093536",
        "population": ""
    },
    {
        "city": "Mardan",
        "state": "Khyber Pakhtunkhwa",
        "country": "Pakistan",
        "population_proper": "",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "34.197943",
        "longitude": "72.04965",
        "population": ""
    },
    {
        "city": "Uthal",
        "state": "Balochistan",
        "country": "Pakistan",
        "population_proper": "",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "25.807222",
        "longitude": "66.621944",
        "population": ""
    },
    {
        "city": "Nankana Sahib",
        "state": "Punjab",
        "country": "Pakistan",
        "population_proper": "",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "31.4475",
        "longitude": "73.697222",
        "population": ""
    },
    {
        "city": "Barkhan",
        "state": "Balochistan",
        "country": "Pakistan",
        "population_proper": "",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "29.897727",
        "longitude": "69.525584",
        "population": ""
    },
    {
        "city": "Hafizabad",
        "state": "Punjab",
        "country": "Pakistan",
        "population_proper": "",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "32.067857",
        "longitude": "73.685449",
        "population": ""
    },
    {
        "city": "Kotli",
        "state": "Azad Kashmir",
        "country": "Pakistan",
        "population_proper": "",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "33.518362",
        "longitude": "73.902203",
        "population": ""
    },
    {
        "city": "Loralai",
        "state": "Balochistan",
        "country": "Pakistan",
        "population_proper": "",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "30.370512",
        "longitude": "68.597949",
        "population": ""
    },
    {
        "city": "Dera Bugti",
        "state": "Balochistan",
        "country": "Pakistan",
        "population_proper": "",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "29.036188",
        "longitude": "69.158493",
        "population": ""
    },
    {
        "city": "Jhang City",
        "state": "Punjab",
        "country": "Pakistan",
        "population_proper": "",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "31.305684",
        "longitude": "72.325941",
        "population": ""
    },
    {
        "city": "Sahibwal",
        "state": "Punjab",
        "country": "Pakistan",
        "population_proper": "",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "30.666667",
        "longitude": "73.1",
        "population": ""
    },
    {
        "city": "Sanghar",
        "state": "Sindh",
        "country": "Pakistan",
        "population_proper": "",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "26.046558",
        "longitude": "68.9481",
        "population": ""
    },
    {
        "city": "Pakpattan",
        "state": "Punjab",
        "country": "Pakistan",
        "population_proper": "",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "30.341044",
        "longitude": "73.386642",
        "population": ""
    },
    {
        "city": "Chakwal",
        "state": "Punjab",
        "country": "Pakistan",
        "population_proper": "",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "32.933376",
        "longitude": "72.858531",
        "population": ""
    },
    {
        "city": "Khushab",
        "state": "Punjab",
        "country": "Pakistan",
        "population_proper": "",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "32.296667",
        "longitude": "72.3525",
        "population": ""
    },
    {
        "city": "Ghotki",
        "state": "Sindh",
        "country": "Pakistan",
        "population_proper": "",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "28.00604",
        "longitude": "69.316077",
        "population": ""
    },
    {
        "city": "Kohlu",
        "state": "Balochistan",
        "country": "Pakistan",
        "population_proper": "",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "29.896505",
        "longitude": "69.253235",
        "population": ""
    },
    {
        "city": "Khuzdar",
        "state": "Balochistan",
        "country": "Pakistan",
        "population_proper": "",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "27.738385",
        "longitude": "66.643365",
        "population": ""
    },
    {
        "city": "Awaran",
        "state": "Balochistan",
        "country": "Pakistan",
        "population_proper": "",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "26.456768",
        "longitude": "65.231436",
        "population": ""
    },
    {
        "city": "Nowshera",
        "state": "Khyber Pakhtunkhwa",
        "country": "Pakistan",
        "population_proper": "",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "34.015828",
        "longitude": "71.981232",
        "population": ""
    },
    {
        "city": "Charsadda",
        "state": "Khyber Pakhtunkhwa",
        "country": "Pakistan",
        "population_proper": "",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "34.148221",
        "longitude": "71.740604",
        "population": ""
    },
    {
        "city": "Qila Abdullah",
        "state": "Balochistan",
        "country": "Pakistan",
        "population_proper": "",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "30.728035",
        "longitude": "66.661174",
        "population": ""
    },
    {
        "city": "Bahawalnagar",
        "state": "Punjab",
        "country": "Pakistan",
        "population_proper": "",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "29.998659",
        "longitude": "73.253604",
        "population": ""
    },
    {
        "city": "Dadu",
        "state": "Sindh",
        "country": "Pakistan",
        "population_proper": "",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "26.730334",
        "longitude": "67.776896",
        "population": ""
    },
    {
        "city": "Alibabad",
        "state": "Gilgit-Baltistan",
        "country": "Pakistan",
        "population_proper": "",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "36.307028",
        "longitude": "74.615449",
        "population": ""
    },
    {
        "city": "Lakki Marwat",
        "state": "Khyber Pakhtunkhwa",
        "country": "Pakistan",
        "population_proper": "",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "32.607953",
        "longitude": "70.911416",
        "population": ""
    },
    {
        "city": "Chilas",
        "state": "Gilgit-Baltistan",
        "country": "Pakistan",
        "population_proper": "",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "35.412867",
        "longitude": "74.104068",
        "population": ""
    },
    {
        "city": "Pishin",
        "state": "Balochistan",
        "country": "Pakistan",
        "population_proper": "",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "30.581762",
        "longitude": "66.994061",
        "population": ""
    },
    {
        "city": "Tank",
        "state": "Khyber Pakhtunkhwa",
        "country": "Pakistan",
        "population_proper": "",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "32.217071",
        "longitude": "70.383154",
        "population": ""
    },
    {
        "city": "Chitral",
        "state": "Khyber Pakhtunkhwa",
        "country": "Pakistan",
        "population_proper": "",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "35.851802",
        "longitude": "71.786358",
        "population": ""
    },
    {
        "city": "Qila Saifullah",
        "state": "Balochistan",
        "country": "Pakistan",
        "population_proper": "",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "30.700766",
        "longitude": "68.359843",
        "population": ""
    },
    {
        "city": "Shikarpur",
        "state": "Sindh",
        "country": "Pakistan",
        "population_proper": "",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "27.957057",
        "longitude": "68.637886",
        "population": ""
    },
    {
        "city": "Panjgur",
        "state": "Balochistan",
        "country": "Pakistan",
        "population_proper": "",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "26.971861",
        "longitude": "64.094594",
        "population": ""
    },
    {
        "city": "Mastung",
        "state": "Balochistan",
        "country": "Pakistan",
        "population_proper": "",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "29.799656",
        "longitude": "66.845527",
        "population": ""
    },
    {
        "city": "Kalat",
        "state": "Balochistan",
        "country": "Pakistan",
        "population_proper": "",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "29.026629",
        "longitude": "66.593607",
        "population": ""
    },
    {
        "city": "Gandava",
        "state": "Balochistan",
        "country": "Pakistan",
        "population_proper": "",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "28.613207",
        "longitude": "67.485643",
        "population": ""
    },
    {
        "city": "Khanewal",
        "state": "Punjab",
        "country": "Pakistan",
        "population_proper": "",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "30.301731",
        "longitude": "71.932124",
        "population": ""
    },
    {
        "city": "Narowal",
        "state": "Punjab",
        "country": "Pakistan",
        "population_proper": "",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "32.1",
        "longitude": "74.883333",
        "population": ""
    },
    {
        "city": "Khairpur",
        "state": "Sindh",
        "country": "Pakistan",
        "population_proper": "",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "27.529483",
        "longitude": "68.761698",
        "population": ""
    },
    {
        "city": "Malakand",
        "state": "Khyber Pakhtunkhwa",
        "country": "Pakistan",
        "population_proper": "",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "34.565609",
        "longitude": "71.930432",
        "population": ""
    },
    {
        "city": "Vihari",
        "state": "Punjab",
        "country": "Pakistan",
        "population_proper": "",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "30.033333",
        "longitude": "72.35",
        "population": ""
    },
    {
        "city": "Saidu Sharif",
        "state": "Khyber Pakhtunkhwa",
        "country": "Pakistan",
        "population_proper": "",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "34.746548",
        "longitude": "72.355675",
        "population": ""
    },
    {
        "city": "Jhelum",
        "state": "Punjab",
        "country": "Pakistan",
        "population_proper": "",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "32.934484",
        "longitude": "73.731018",
        "population": ""
    },
    {
        "city": "Mandi Bahauddibn",
        "state": "Punjab",
        "country": "Pakistan",
        "population_proper": "",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "32.587037",
        "longitude": "73.491231",
        "population": ""
    },
    {
        "city": "Bhakkar",
        "state": "Punjab",
        "country": "Pakistan",
        "population_proper": "",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "31.625247",
        "longitude": "71.06574",
        "population": ""
    },
    {
        "city": "Toba Tek Singh",
        "state": "Punjab",
        "country": "Pakistan",
        "population_proper": "",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "30.974326",
        "longitude": "72.482694",
        "population": ""
    },
    {
        "city": "Jamshoro",
        "state": "Sindh",
        "country": "Pakistan",
        "population_proper": "",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "25.436078",
        "longitude": "68.280172",
        "population": ""
    },
    {
        "city": "Kharan",
        "state": "Balochistan",
        "country": "Pakistan",
        "population_proper": "",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "28.584585",
        "longitude": "65.415007",
        "population": ""
    },
    {
        "city": "Umarkot",
        "state": "Sindh",
        "country": "Pakistan",
        "population_proper": "",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "25.36157",
        "longitude": "69.736241",
        "population": ""
    },
    {
        "city": "Hangu",
        "state": "Khyber Pakhtunkhwa",
        "country": "Pakistan",
        "population_proper": "",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "33.53198",
        "longitude": "71.059499",
        "population": ""
    },
    {
        "city": "Timargara",
        "state": "Khyber Pakhtunkhwa",
        "country": "Pakistan",
        "population_proper": "",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "34.826595",
        "longitude": "71.844226",
        "population": ""
    },
    {
        "city": "Gakuch",
        "state": "Gilgit-Baltistan",
        "country": "Pakistan",
        "population_proper": "",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "36.176826",
        "longitude": "73.763834",
        "population": ""
    },
    {
        "city": "Jacobabad",
        "state": "Sindh",
        "country": "Pakistan",
        "population_proper": "",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "28.281873",
        "longitude": "68.437613",
        "population": ""
    },
    {
        "city": "Alpurai",
        "state": "Khyber Pakhtunkhwa",
        "country": "Pakistan",
        "population_proper": "",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "34.920577",
        "longitude": "72.632556",
        "population": ""
    },
    {
        "city": "Mianwali",
        "state": "Punjab",
        "country": "Pakistan",
        "population_proper": "",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "32.574095",
        "longitude": "71.526386",
        "population": ""
    },
    {
        "city": "Musa Khel Bazar",
        "state": "Balochistan",
        "country": "Pakistan",
        "population_proper": "",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "30.859443",
        "longitude": "69.82208",
        "population": ""
    },
    {
        "city": "Naushahro Fibroz",
        "state": "Sindh",
        "country": "Pakistan",
        "population_proper": "",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "26.840104",
        "longitude": "68.122651",
        "population": ""
    },
    {
        "city": "New Mibrpur",
        "state": "Azad Kashmir",
        "country": "Pakistan",
        "population_proper": "",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "33.147815",
        "longitude": "73.751867",
        "population": ""
    },
    {
        "city": "Daggar",
        "state": "Khyber Pakhtunkhwa",
        "country": "Pakistan",
        "population_proper": "",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "34.511059",
        "longitude": "72.484375",
        "population": ""
    },
    {
        "city": "Eidgah",
        "state": "Gilgit-Baltistan",
        "country": "Pakistan",
        "population_proper": "",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "35.347115",
        "longitude": "74.856317",
        "population": ""
    },
    {
        "city": "Sibi",
        "state": "Balochistan",
        "country": "Pakistan",
        "population_proper": "",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "29.542989",
        "longitude": "67.87726",
        "population": ""
    },
    {
        "city": "Dalbandibn",
        "state": "Balochistan",
        "country": "Pakistan",
        "population_proper": "",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "28.888456",
        "longitude": "64.406156",
        "population": ""
    },
    {
        "city": "Rajanpur",
        "state": "Punjab",
        "country": "Pakistan",
        "population_proper": "",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "29.103513",
        "longitude": "70.325038",
        "population": ""
    },
    {
        "city": "Leiah",
        "state": "Punjab",
        "country": "Pakistan",
        "population_proper": "",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "30.961279",
        "longitude": "70.939043",
        "population": ""
    },
    {
        "city": "Upper Dir",
        "state": "Khyber Pakhtunkhwa",
        "country": "Pakistan",
        "population_proper": "",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "35.207398",
        "longitude": "71.876801",
        "population": ""
    },
    {
        "city": "Tando Muhammad Khan",
        "state": "Sindh",
        "country": "Pakistan",
        "population_proper": "",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "25.123007",
        "longitude": "68.535773",
        "population": ""
    },
    {
        "city": "Attock City",
        "state": "Punjab",
        "country": "Pakistan",
        "population_proper": "",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "33.76671",
        "longitude": "72.359766",
        "population": ""
    },
    {
        "city": "Rawala Kot",
        "state": "Azad Kashmir",
        "country": "Pakistan",
        "population_proper": "",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "33.857816",
        "longitude": "73.760426",
        "population": ""
    },
    {
        "city": "Swabi",
        "state": "Khyber Pakhtunkhwa",
        "country": "Pakistan",
        "population_proper": "",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "34.120181",
        "longitude": "72.46982",
        "population": ""
    },
    {
        "city": "Kandhkot",
        "state": "Sindh",
        "country": "Pakistan",
        "population_proper": "",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "28.243963",
        "longitude": "69.182354",
        "population": ""
    },
    {
        "city": "Dasu",
        "state": "Khyber Pakhtunkhwa",
        "country": "Pakistan",
        "population_proper": "",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "35.291687",
        "longitude": "73.290602",
        "population": ""
    },
    {
        "city": "Athmuqam",
        "state": "Azad Kashmir",
        "country": "Pakistan",
        "population_proper": "",
        "iso2": "PK",
        "capital": "minor",
        "latitude": "34.571733",
        "longitude": "73.897236",
        "population": ""
    },
    {
        "city": "Hunza",
        "state": "",
        "country": "Pakistan",
        "population_proper": "",
        "iso2": "PK",
        "capital": "",
        "latitude": "",
        "longitude": "",
        "population": ""
    }
];